export const payload = {
  user: {
    id: 'UP0RTRL02',
  },
  actions:[{
    action_id: 'user_trip_change_location_5',
    block_id: 'user_trip_select_location',
    value: '107',
  }],
};

export const homeBases = [{ id: 5,
  name: 'Cairo',
  countryId: 5,
  addressId: null,
  locationId: null,
  country: { name: 'Egypt' } },
  { id: 4,
    name: 'Kampala',
    countryId: 4,
    addressId: 14,
    locationId: 40,
    country: { name: 'Uganda' } },
  { id: 3,
    name: 'Kigali',
    countryId: 2,
    addressId: 20,
    locationId: 41,
    country: { name: 'Rwanda' } },
  { id: 1,
    name: 'Lagos',
    countryId: 1,
    addressId: null,
    locationId: null,
    country: { name: 'Nigeria' } },
  { id: 2,
    name: 'Nairobi',
    countryId: 3,
    addressId: 1,
    locationId: 39,
    country: { name: 'Kenya' },
  },
];

export const userHomeBase = {
  id: 3,
  name: 'Kigali',
  addressId: 20,
  locationId: 41,
  country: { name: 'Rwanda' },
};
